# Generated by Django 3.2.9 on 2021-11-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
